---
- name: Install mariadb related packages
  ansible.builtin.package:
    name: "{{ mariadb_packages }}"
    state: present
  notify:
    - Mariadb restart daemon
    - Mariadb remove anonymous users
    - Mariadb remove test database

- name: Create mariadb configuration directory
  ansible.builtin.file:
    path: "{{ mariadb_conf_dir }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
    seuser: system_u
    serole: object_r
    setype: mysqld_etc_t
    selevel: s0

- name: Remove stub configurations
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ mariadb_conf_remove }}"
  when: mariadb_conf_remove is defined and item is defined and item
