---
- name: Mariadb check config and restart
  ansible.builtin.shell: "{{ mariadb_server_bin }} --help --verbose --skip-networking 1>/dev/null" # noqa: no-changed-when
  notify:
    - Mariadb restart daemon

- name: Mariadb restart daemon
  ansible.builtin.service:
    name: "{{ mariadb_service }}"
    state: restarted

- name: Mariadb remove anonymous users
  community.mysql.mysql_user:
    name: ""
    host: "{{ item }}"
    login_unix_socket: "{{ mariadb_socket }}"
    state: absent
  with_items: "{{ mariadb_anon_user_hosts }}"

- name: Mariadb remove test database
  community.mysql.mysql_db:
    name: test
    login_unix_socket: "{{ mariadb_socket }}"
    state: absent
