---
name: Publish on Ansible Galaxy

"on":
  push:
    branches:
      - master

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          persist-credentials: false
      - name: galaxy
        uses: robertdebock/galaxy-action@7d89099e09f4385ec4b53eb58c0d120f1ad806dd # 1.2.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
          git_branch: master
